#!/bin/sh
#
# Copyright (c) 2023-2024 Bradley Larrick. All rights reserved.
#
# Licensed under the Apache License v2.0
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
REPO=${HOME}/.m2/repository
PGM_CLASSES=target/classes

cp=${PGM_CLASSES}:$REPO/info/picocli/picocli/4.7.7/picocli-4.7.7.jar

java -cp "$cp" org.natuna.loader.Loader "$@"
